blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://github.com/BirdeezHacker77/Songseek/discussions
    about: For support questions and general chat.
  - name: Documentation
    url: https://github.com/BirdeezHacker77/Songseek
    about: Check the docs before opening an issue.
